### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [kindlingscript/initialscriptings#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by kindlingscript** [comment]
Thanks for the heads up on that issue, Ken! Added the viewport meta tag to my head element, and that looks to have solved the problem. :)

**Comment by kenmazaika** [comment]
Thumbs up, Rebecca!  Your code looks great! :) :+1:
